### PR TITLE
Fix: issue #18

### PR DESCRIPTION
**Pull request by zhanyigo**
Can not generate the code, When the app haven't testFramework

### CODE REVIEW

**Comment by cbornet** [comment]
Thanks for your contribution ! I would have expected testFrameworks to be an empty array instead of null...

**Comment by zhanyigo** [comment]
So, I do it?

**Comment by cbornet** [comment]
No your last commit was not needed. I was OK with the initial fix ! My comment was about the main generator. Sorry for the confusion.

**Comment by cbornet** [comment]
I cherry-picked your first commit (contribution is credited to you). Thanks for the contribution !

**Comment by zhanyigo** [comment]
@cbornet NP! This project is great. Thank you.

**Pull request closed without merging**
